### PR TITLE
TrueColor on Mac and Return Prompt after animation

### PR DESCRIPTION
**Pull request by shelldandy**
💅

### CODE REVIEW

**Comment by shelldandy** [comment]
Also added a better color checker dependency

https://github.com/chalk/supports-color

**Comment by robertmarsal** [comment]
Hi @mike3run, thank you very much for this. The code changes look great, and are probably more compatible with the systems out there, but can you please reverse the formatting changes from the last commit? I am happy with how the formatting was previously. 

Regards,
Rob

**Comment by shelldandy** [comment]
It's fine, really
https://standardjs.com

https://www.youtube.com/watch?v=Qlr-FGbhKaI
http://blog.izs.me/post/2353458699/an-open-letter-to-javascript-leaders-regarding
http://inimino.org/~inimino/blog/javascript_semicolons
https://www.youtube.com/watch?v=gsfbh17Ax9I

**Comment by shelldandy** [comment]
sadddd

Going back now

**Comment by shelldandy** [comment]
All set @robertboloc

**Comment by robertmarsal** [comment]
Amazing! Thank you so much for your contribution. I will look into the standardjs.com recommendation and see if I can adopt it for my projects :+1:

**Pull request merged**
